/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "k8s.io/sample-controller/pkg/apis/nicolecontroller/v1alpha1"
	scheme "k8s.io/sample-controller/pkg/client_icecream/clientset/versioned/scheme"
)

// IcecreamsGetter has a method to return a IcecreamInterface.
// A group's client should implement this interface.
type IcecreamsGetter interface {
	Icecreams(namespace string) IcecreamInterface
}

// IcecreamInterface has methods to work with Icecream resources.
type IcecreamInterface interface {
	Create(ctx context.Context, icecream *v1alpha1.Icecream, opts v1.CreateOptions) (*v1alpha1.Icecream, error)
	Update(ctx context.Context, icecream *v1alpha1.Icecream, opts v1.UpdateOptions) (*v1alpha1.Icecream, error)
	UpdateStatus(ctx context.Context, icecream *v1alpha1.Icecream, opts v1.UpdateOptions) (*v1alpha1.Icecream, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Icecream, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IcecreamList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Icecream, err error)
	IcecreamExpansion
}

// icecreams implements IcecreamInterface
type icecreams struct {
	client rest.Interface
	ns     string
}

// newIcecreams returns a Icecreams
func newIcecreams(c *SamplecontrollerV1alpha1Client, namespace string) *icecreams {
	return &icecreams{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the icecream, and returns the corresponding icecream object, and an error if there is any.
func (c *icecreams) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Icecream, err error) {
	result = &v1alpha1.Icecream{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("icecreams").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Icecreams that match those selectors.
func (c *icecreams) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IcecreamList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IcecreamList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("icecreams").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested icecreams.
func (c *icecreams) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("icecreams").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a icecream and creates it.  Returns the server's representation of the icecream, and an error, if there is any.
func (c *icecreams) Create(ctx context.Context, icecream *v1alpha1.Icecream, opts v1.CreateOptions) (result *v1alpha1.Icecream, err error) {
	result = &v1alpha1.Icecream{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("icecreams").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(icecream).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a icecream and updates it. Returns the server's representation of the icecream, and an error, if there is any.
func (c *icecreams) Update(ctx context.Context, icecream *v1alpha1.Icecream, opts v1.UpdateOptions) (result *v1alpha1.Icecream, err error) {
	result = &v1alpha1.Icecream{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("icecreams").
		Name(icecream.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(icecream).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *icecreams) UpdateStatus(ctx context.Context, icecream *v1alpha1.Icecream, opts v1.UpdateOptions) (result *v1alpha1.Icecream, err error) {
	result = &v1alpha1.Icecream{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("icecreams").
		Name(icecream.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(icecream).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the icecream and deletes it. Returns an error if one occurs.
func (c *icecreams) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("icecreams").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *icecreams) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("icecreams").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched icecream.
func (c *icecreams) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Icecream, err error) {
	result = &v1alpha1.Icecream{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("icecreams").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
