/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "k8s.io/sample-controller/pkg/apis/nicolecontroller/v1alpha1"
)

// FakeIcecreams implements IcecreamInterface
type FakeIcecreams struct {
	Fake *FakeSamplecontrollerV1alpha1
	ns   string
}

var icecreamsResource = schema.GroupVersionResource{Group: "samplecontroller.k8s.io", Version: "v1alpha1", Resource: "icecreams"}

var icecreamsKind = schema.GroupVersionKind{Group: "samplecontroller.k8s.io", Version: "v1alpha1", Kind: "Icecream"}

// Get takes name of the icecream, and returns the corresponding icecream object, and an error if there is any.
func (c *FakeIcecreams) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Icecream, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(icecreamsResource, c.ns, name), &v1alpha1.Icecream{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Icecream), err
}

// List takes label and field selectors, and returns the list of Icecreams that match those selectors.
func (c *FakeIcecreams) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IcecreamList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(icecreamsResource, icecreamsKind, c.ns, opts), &v1alpha1.IcecreamList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IcecreamList{ListMeta: obj.(*v1alpha1.IcecreamList).ListMeta}
	for _, item := range obj.(*v1alpha1.IcecreamList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested icecreams.
func (c *FakeIcecreams) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(icecreamsResource, c.ns, opts))

}

// Create takes the representation of a icecream and creates it.  Returns the server's representation of the icecream, and an error, if there is any.
func (c *FakeIcecreams) Create(ctx context.Context, icecream *v1alpha1.Icecream, opts v1.CreateOptions) (result *v1alpha1.Icecream, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(icecreamsResource, c.ns, icecream), &v1alpha1.Icecream{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Icecream), err
}

// Update takes the representation of a icecream and updates it. Returns the server's representation of the icecream, and an error, if there is any.
func (c *FakeIcecreams) Update(ctx context.Context, icecream *v1alpha1.Icecream, opts v1.UpdateOptions) (result *v1alpha1.Icecream, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(icecreamsResource, c.ns, icecream), &v1alpha1.Icecream{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Icecream), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIcecreams) UpdateStatus(ctx context.Context, icecream *v1alpha1.Icecream, opts v1.UpdateOptions) (*v1alpha1.Icecream, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(icecreamsResource, "status", c.ns, icecream), &v1alpha1.Icecream{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Icecream), err
}

// Delete takes name of the icecream and deletes it. Returns an error if one occurs.
func (c *FakeIcecreams) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(icecreamsResource, c.ns, name), &v1alpha1.Icecream{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIcecreams) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(icecreamsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IcecreamList{})
	return err
}

// Patch applies the patch and returns the patched icecream.
func (c *FakeIcecreams) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Icecream, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(icecreamsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Icecream{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Icecream), err
}
